FROM node:20-alpine

WORKDIR /app

# Instalar herramientas adicionales para compilación
RUN apk add --no-cache python3 make g++ git

# Instalar dependencias primero (para aprovechar la caché de Docker)
COPY package*.json ./
RUN npm install

# Aseguramos que la base de datos tenga permisos correctos
RUN mkdir -p /app/data
RUN chmod 777 /app/data

EXPOSE 3000

# Usar un CMD que pueda ser fácilmente sobrescrito
CMD ["npm", "run", "dev"]