# Base image for building the application
FROM node:20

# Set working directory
WORKDIR /app

# Install nodemon for hot-reloading
RUN npm install -g nodemon

# Install project dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Set development environment and log level
ENV NODE_ENV=development
ENV LOG_LEVEL=debug

# Nodemon
EXPOSE 3000

# Start the application
CMD ["nodemon", "--watch", "./", "--ext", "js,json", "--ignore", "node_modules/", "--ignore", "dist/", "--legacy-watch", "src/app.js"]
