FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
# RUN npm install

COPY . .

ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

EXPOSE 80

CMD ["node_modules/.bin/vite"]
