# Usa la imagen oficial de LogStash
FROM docker.elastic.co/logstash/logstash:7.17.4

# Copia la configuración de LogStash
COPY conf/logstash.conf /usr/share/logstash/pipeline/logstash.conf

EXPOSE 5044
