# Base image for building the application
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install nodemon for hot-reloading
RUN npm install -g nodemon

# Install project dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Set development environment and log level
ENV NODE_ENV=development
ENV LOG_LEVEL=debug

# Add metadata labels
LABEL org.opencontainers.image.vendor="Kobayashi Corp."
LABEL org.opencontainers.image.source="https://github.com/Kobayashi82/ft_transcendence"
LABEL org.opencontainers.image.description="API Gateway"
LABEL org.opencontainers.image.version="1.0.0"
LABEL org.opencontainers.image.created="2025-03-27"
LABEL maintainer="Kobayashi82@outlook.com"

# Nodemon
EXPOSE 3000

# Start the application
CMD ["nodemon", "--watch", "./", "--ext", "js,json", "--ignore", "node_modules/", "--ignore", "dist/", "--legacy-watch", "src/app.js"]
